# This is for testing and exercising numpy, pandas, and other staffs 

In [1]:
print("ok")

ok


In [3]:
import numpy as np
import pandas as pd

In [12]:
arr = np.arange(10, 30)
print(arr)
print(len(arr))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
20


In [20]:
arr1 = arr.reshape(4, 5)
print(arr1)
print(arr1.shape, arr1.ndim, arr1.size)  

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
(4, 5) 2 20


In [22]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [28]:
print(arr[1, ::])
print(arr[::, -1])
print(arr[1:3, 1:3])

[5 6 7 8]
[ 4  8 12 16]
[[ 6  7]
 [10 11]]
